spring.application.name=microservice-hospital
server.port=4200

# application.properties
#eureka.client.enabled=false

# ====================== DATASOURCE MySQL ======================
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true

spring.datasource.url=jdbc:mysql://localhost:3306/opcl_p11_hospital?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=archi_p11
spring.datasource.password=Openclassrooms2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ====================== JPA / HIBERNATE ======================
# Mode de creation/mise a jour automatique des tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
# Afficher les requetes SQL dans la console
spring.jpa.show-sql=true

# Formater joliment les requetes SQL
spring.jpa.properties.hibernate.format_sql=true

# Dialecte MySQL (Spring Boot le detecte souvent tout seul, mais c'est plus explicite)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect