spring.application.name=micro-bed-availbility

server.port=4300

# application.properties
eureka.client.enabled=false

# ====================== DATASOURCE MySQL ======================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.datasource.url=jdbc:mysql://localhost:3306/opcl_p11_bedavailability?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=archi_p11
spring.datasource.password=Openclassrooms2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ====================== JPA / HIBERNATE ======================
# Mode de création/mise à jour automatique des tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
# Afficher les requêtes SQL dans la console (très utile en dev)
spring.jpa.show-sql=true

# Formater joliment les requêtes SQL
spring.jpa.properties.hibernate.format_sql=true

# Dialecte MySQL (Spring Boot le détecte souvent tout seul, mais c?est plus explicite)
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
