spring.application.name=microservice-bed-availability
server.port=4300

feign.client.url.microservice-gateway=http://localhost:8100

# application.properties
eureka.client.enabled=true
eureka.client.serviceUrl.defaultZone: http://localhost:9102/eureka/


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Optionnel mais recommande
spring.rabbitmq.template.exchange=app.exchange
spring.rabbitmq.template.routing-key=appointment.events


