spring.application.name=micro-gateway
spring.main.allow-bean-definition-overriding=true

#spring.security.enabled=false
#security.basic.enabled=false

server.port=8100
#spring.main.web-application-type=reactive
# logging.level.org.springframework=DEBUG

#logging.level.org.springframework.cloud.gateway.route=DEBUG
logging.level.org.springframework.cloud.gateway=TRACE

#logging.level.reactor.netty.http.server=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security.core.userdetails=DEBUG

app.gateway.basicurl=localhost


################### Eureka Configuration ##########################
eureka.client.serviceUrl.defaultZone: http://localhost:9102/eureka/
# eureka.client.enabled=false

################### Security Configuration ##########################
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.timeout=1m
server.reactive.session.timeout=1m


#spring.cloud.gateway.server.webmvc.routes[0].id=MicroserviceHospital
#spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:4200
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/Hospital/**
#spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# spring.cloud.gateway.server.webmvc.routes[0].id=MicroServiceAppointment
# spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:4100
# spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/Patient/**
# spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# spring.cloud.gateway.server.webmvc.routes[1].id=MicroserviceHospital
# spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:4200
# spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/Hospital/**
# spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

# spring.cloud.gateway.server.webmvc.routes[2].id=MicroserviceBedAvailability
# spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:4300
# spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/Bed/**
# spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1